title: "Isabel (Izzy) Allum"
description: "CS Master's Student Portfolio"
baseurl: "" # root
url: "https://itallum.com" # change if you use a subdomain

collections:
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag